TTS_dataset: "voice_cloning_train"

model_name: "canopylabs/orpheus-tts-0.1-pretrained"

# Training Args
epochs: 3
batch_size: 1
number_processes: 1
pad_token: 128263
save_steps: 5000
learning_rate: 5.0e-5

# Naming and paths
save_folder: "voice_cloning/models"
project_name: "voice-cloning"
run_name: "voice-cloning"
